// Generated by Wrangler on Sun May 12 2024 12:42:57 GMT+0300 (Israel Daylight Time)
// by running `wrangler types`

interface Env {
	STORAGE: KVNamespace;
	BOT_INFO: "{\"id\":6998636845,\"is_bot\":true,\"first_name\":\"DoctorNotifier\",\"username\":\"doctornotifier_bot\",\"can_join_groups\":true,\"can_read_all_group_messages\":false,\"supports_inline_queries\":false,\"can_connect_to_business\":false}";
	TELEGRAM_BOT_TOKEN: string;
}
