#:schema node_modules/wrangler/config-schema.json
name = "doctor-notifier-webhook"
main = "src/index.ts"
compatibility_date = "2024-05-02"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "STORAGE"
id = "9cda716cb66f45eb9ccf7d8bf1d99f8a"

[vars]
BOT_INFO = "{\"id\":6998636845,\"is_bot\":true,\"first_name\":\"DoctorNotifier\",\"username\":\"doctornotifier_bot\",\"can_join_groups\":true,\"can_read_all_group_messages\":false,\"supports_inline_queries\":false,\"can_connect_to_business\":false}"
